//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporting_Inrerface.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Reporting_Inrerface.ServiceReference2.HelloWorldResponse HelloWorld(Reporting_Inrerface.ServiceReference2.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Reporting_Inrerface.ServiceReference2.HelloWorldResponse> HelloWorldAsync(Reporting_Inrerface.ServiceReference2.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name Id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTime", ReplyAction="*")]
        Reporting_Inrerface.ServiceReference2.getTimeResponse getTime(Reporting_Inrerface.ServiceReference2.getTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTime", ReplyAction="*")]
        System.Threading.Tasks.Task<Reporting_Inrerface.ServiceReference2.getTimeResponse> getTimeAsync(Reporting_Inrerface.ServiceReference2.getTimeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Reporting_Inrerface.ServiceReference2.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Reporting_Inrerface.ServiceReference2.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Reporting_Inrerface.ServiceReference2.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Reporting_Inrerface.ServiceReference2.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTime", Namespace="http://tempuri.org/", Order=0)]
        public Reporting_Inrerface.ServiceReference2.getTimeRequestBody Body;
        
        public getTimeRequest() {
        }
        
        public getTimeRequest(Reporting_Inrerface.ServiceReference2.getTimeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTimeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Id;
        
        public getTimeRequestBody() {
        }
        
        public getTimeRequestBody(string Id) {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTimeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Reporting_Inrerface.ServiceReference2.getTimeResponseBody Body;
        
        public getTimeResponse() {
        }
        
        public getTimeResponse(Reporting_Inrerface.ServiceReference2.getTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTimeResult;
        
        public getTimeResponseBody() {
        }
        
        public getTimeResponseBody(string getTimeResult) {
            this.getTimeResult = getTimeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Reporting_Inrerface.ServiceReference2.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Reporting_Inrerface.ServiceReference2.WebService1Soap>, Reporting_Inrerface.ServiceReference2.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Reporting_Inrerface.ServiceReference2.HelloWorldResponse Reporting_Inrerface.ServiceReference2.WebService1Soap.HelloWorld(Reporting_Inrerface.ServiceReference2.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Reporting_Inrerface.ServiceReference2.HelloWorldRequest inValue = new Reporting_Inrerface.ServiceReference2.HelloWorldRequest();
            inValue.Body = new Reporting_Inrerface.ServiceReference2.HelloWorldRequestBody();
            Reporting_Inrerface.ServiceReference2.HelloWorldResponse retVal = ((Reporting_Inrerface.ServiceReference2.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Reporting_Inrerface.ServiceReference2.HelloWorldResponse> Reporting_Inrerface.ServiceReference2.WebService1Soap.HelloWorldAsync(Reporting_Inrerface.ServiceReference2.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Reporting_Inrerface.ServiceReference2.HelloWorldResponse> HelloWorldAsync() {
            Reporting_Inrerface.ServiceReference2.HelloWorldRequest inValue = new Reporting_Inrerface.ServiceReference2.HelloWorldRequest();
            inValue.Body = new Reporting_Inrerface.ServiceReference2.HelloWorldRequestBody();
            return ((Reporting_Inrerface.ServiceReference2.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Reporting_Inrerface.ServiceReference2.getTimeResponse Reporting_Inrerface.ServiceReference2.WebService1Soap.getTime(Reporting_Inrerface.ServiceReference2.getTimeRequest request) {
            return base.Channel.getTime(request);
        }
        
        public string getTime(string Id) {
            Reporting_Inrerface.ServiceReference2.getTimeRequest inValue = new Reporting_Inrerface.ServiceReference2.getTimeRequest();
            inValue.Body = new Reporting_Inrerface.ServiceReference2.getTimeRequestBody();
            inValue.Body.Id = Id;
            Reporting_Inrerface.ServiceReference2.getTimeResponse retVal = ((Reporting_Inrerface.ServiceReference2.WebService1Soap)(this)).getTime(inValue);
            return retVal.Body.getTimeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Reporting_Inrerface.ServiceReference2.getTimeResponse> Reporting_Inrerface.ServiceReference2.WebService1Soap.getTimeAsync(Reporting_Inrerface.ServiceReference2.getTimeRequest request) {
            return base.Channel.getTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Reporting_Inrerface.ServiceReference2.getTimeResponse> getTimeAsync(string Id) {
            Reporting_Inrerface.ServiceReference2.getTimeRequest inValue = new Reporting_Inrerface.ServiceReference2.getTimeRequest();
            inValue.Body = new Reporting_Inrerface.ServiceReference2.getTimeRequestBody();
            inValue.Body.Id = Id;
            return ((Reporting_Inrerface.ServiceReference2.WebService1Soap)(this)).getTimeAsync(inValue);
        }
    }
}
